#define DEEPONE_ATTACK_SPEED (CLICK_CD_MELEE * 1.75)
#define DEEPONE_HEALTH 140
#define DEEPONE_MOVEMENT_SPEED 0.5 SECONDS
#define FISH_ATTACK_SPEED (CLICK_CD_MELEE * 2)
#define FISH_HEALTH 40
#define FISH_MOVEMENT_SPEED 1 SECONDS
#define SHARK_HEALTH 350
